version: '3'

services:
  ci-build:
    image: microsoft/dotnet:2.1-sdk
    volumes:
      - .:/src
    working_dir: /src
    environment:
      - GRAYLOG_HOST=graylog
    command: >
      /bin/bash -c '
        versionArg=$$([[ ! -z "$VERSION" ]] && echo "/p:Version=$VERSION" || echo "") &&
        dotnet build -c Release $$versionArg &&
        find test/*/*Tests.csproj | xargs -n 1 dotnet test -c Release --no-build
      '
